version: '2'

services:
  camunda:
    build:
      context: ./camunda-tomcat-hardened
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=db:5432

  db:
    build: ./postgres-camunda-ee
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda

